{{- if .Values.auth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pylos.fullname" . }}-auth
  labels:
    {{- include "pylos.labels" . | nindent 4 }}
spec:
  basicAuth:
    secret: {{ include "pylos.fullname" . }}-auth
{{- end }}
