{{- if .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pylos.fullname" . }}-auth
  labels:
    {{- include "pylos.labels" . | nindent 4 }}
type: Opaque
stringData:
  users: {{ required "auth.users (htpasswd-Zeile) fehlt bei auth.enabled" .Values.auth.users | quote }}
{{- end }}
